### PR TITLE
merge feature/btc to main

### PR DESCRIPTION
**Pull request by H-Blues**

### CODE REVIEW

**Comment by H-Blues** [comment]
Hi @BuildWithData 

I tried to merge `feature/btc` to `main`, but I'm not sure if you want to standardize the git commit message.

Please tell me if I did it wrong.

**Comment by BuildWithData** [comment]
this is the first contribution we received, thanks a lot !!!

I have been scraping ETH ETF data, but missing the extraction step, would you like to undertake this task ?

**Comment by H-Blues** [comment]
I can try when I have free time. Please let me know which branch to do

**Comment by BuildWithData** [comment]
many thanks

just added all the code on this branch ```feature/all_eth_etf```

when you are done with one, just create a separate branch called ```feature/etf_name``` and push it here so I can test it :)

**Comment by BuildWithData** [comment]
thanks for your help, have a look here https://github.com/BuildWithData/BTC-ETF-Tracker/issues/98

**Pull request merged**
